# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paroles Politiques
tagline:          ''
description:      Discours sans filtres
url:              ''
baseurl:          /paroles-politiques-fr

author:
  name:           Paroles Politiques
  url:            ''

paginate:         5

plugins:
  - jekyll-paginate
