# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paroles Politiques
tagline:          ''
description:      Discours bruts
url:              ''
baseurl:          /paroles-politiques-fr

author:
  name:           Paroles Politiques
  url:            ''

paginate:         3

plugins:
  - jekyll-paginate
