# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Paroles Politiques
tagline:          ''
description:      'Tous les discours sans aucun filtre'
url:              ''
baseurl:          /

author:
  name:           'Paroles Politiques'
  url:            ''

paginate:         5

plugins:
  - jekyll-paginate
