# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Parole Politique
tagline:          ''
description:      Discours bruts
url:              ''
baseurl:          /paroles-politiques-fr

author:
  name:           "@ParolePol"
  url:            ''

paginate:         10

plugins:
  - jekyll-paginate
